### ISSUE TITLE
Sample doesn't run

### ISSUE THREAD

**Issue by Tailslide** [amuste/DnetIndexedDb#40]
I get the following error running the sample application. 

```
Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer: Warning: Unhandled exception rendering component: Cannot read property 'dbModel' of undefined
TypeError: Cannot read property 'dbModel' of undefined
    at Object.getExtent (https://localhost:44357/_content/DnetIndexedDb/dnet-indexeddb.js:1071:75)
    at https://localhost:44357/_framework/blazor.server.js:1:70045
    at new Promise (<anonymous>)
    at e.beginInvokeJSFromDotNet (https://localhost:44357/_framework/blazor.server.js:1:70011)
    at https://localhost:44357/_framework/blazor.server.js:1:26293
    at Array.forEach (<anonymous>)
    at e.invokeClientMethod (https://localhost:44357/_framework/blazor.server.js:1:26263)
    at e.processIncomingData (https://localhost:44357/_framework/blazor.server.js:1:24201)
    at e.connection.onreceive (https://localhost:44357/_framework/blazor.server.js:1:17286)
    at WebSocket.i.onmessage (https://localhost:44357/_framework/blazor.server.js:1:46503)
```

**Comment by dharmaturtle** [comment]
Fixed in https://github.com/amuste/DnetIndexedDb/pull/43
