### ISSUE TITLE
Could not find 'dnetindexeddbinterop.openDb' 

### ISSUE THREAD

**Issue by sveins12** [amuste/DnetIndexedDb#56]
I get this exceptions on all operations:

* Could not find 'dnetindexeddbinterop.openDb' 
* Could not find 'dnetindexeddbinterop.addItems'
* and so forth

I have used the debugger tool in the browser and checked that windows.dnetindexeddbinterop exists. 
What could I have been missing?

More exception details:
```
'Could not find 'dnetindexeddbinterop.addItems' ('dnetindexeddbinterop' was undefined).\nError: Could not find 'dnetindexeddbinterop.addItems' ('dnetindexeddbinterop' was undefined).\n    at https://localhost:7092/_framework/blazor.webassembly.js:1:328\n    at Array.forEach (<anonymous>)\n    at a.findFunction (https://localhost:7092/_framework/blazor.webassembly.js:1:296)\n    at _ (https://localhost:7092/_framework/blazor.webassembly.js:1:2437)\n    at https://localhost:7092/_framework/blazor.webassembly.js:1:3325\n    at new Promise (<anonymous>)\n    at Object.beginInvokeJSFromDotNet (https://localhost:7092/_framework/blazor.webassembly.js:1:3306)\n    at Object.St [as invokeJSFromDotNet] (https://localhost:7092/_framework/blazor.webassembly.js:1:59938)\n    at _mono_wasm_invoke_js_blazor (https://localhost:7092/_framework/dotnet.6.0.9.rnz6vdon31.js:1:195300)\n    at wasm://wasm/00971d1a:wasm-function[219]:0x1a492'
```

**Comment by benbaker76** [comment]
Because I'm using WebPack I had to change:

```js
var Rx = window['rxjs'];
```
to
```js
var Rx = require('rxjs');
```

In `dnet-indexeddb.js`
